# Generated by Django 4.2.7 on 2023-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
