# Generated by Django 5.1.2 on 2024-12-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='postImage',
        ),
    ]
