# Generated by Django 5.1.2 on 2025-02-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_post_image_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postVideo',
            field=models.FileField(blank=True, null=True, upload_to='post_video'),
        ),
    ]
