# Generated by Django 5.1.2 on 2025-07-26 16:40

import social.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_postvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, storage=social.storage_backends.PublicMediaStorage(), upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postVideo',
            field=models.FileField(blank=True, null=True, storage=social.storage_backends.VideoStorage(), upload_to='post_video'),
        ),
    ]
