# Generated by Django 5.1.2 on 2025-08-05 10:10

import social.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_postimage_alter_post_postvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, storage=social.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
