# Generated by Django 5.1.2 on 2025-01-04 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,),
            preserve_default=False,
        ),
    ]
