# Generated by Django 5.1.2 on 2025-02-05 01:09

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_receiver_alter_message_sender'),
        ('user_profile', '0005_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=chat.models.default_userprofile, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=chat.models.default_userprofile, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user_profile.userprofile'),
        ),
    ]
