# Generated by Django 5.1.2 on 2025-03-06 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0005_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_requests', to='user_profile.userprofile')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='user_profile.userprofile')),
            ],
        ),
    ]
