# Generated by Django 3.2.9 on 2021-11-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='deb',
            new_name='dob',
        ),
    ]
