# Generated by Django 5.1.2 on 2024-11-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_deb_userprofile_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='owner',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lives_in',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='studies_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='works_at',
        ),
    ]
