# Generated by Django 5.1.2 on 2024-11-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_owner_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
