# Generated by Django 5.1.2 on 2025-07-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_is_online_userprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
